import React from 'react'
import { DocsThemeConfig } from 'nextra-theme-docs'

const config: DocsThemeConfig = {
  logo: <span>testphu4</span>,
  project: {
    link: 'https://github.com/Jolli-sample-repos/testphu4',
  },
  docsRepositoryBase: 'https://github.com/Jolli-sample-repos/testphu4',
  footer: {
    text: 'testphu4 - Generated by Jolli',
  },
  useNextSeoProps() {
    return {
      titleTemplate: '%s – testphu4'
    }
  },
  head: (
    <>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta property="og:title" content="testphu4" />
      <meta property="og:description" content="Documentation for testphu4" />
    </>
  )
}

export default config
